### ISSUE TITLE
add Harry, Goomba, Mario & Hogwarts pumpkin to Test Data

### ISSUE THREAD

**Issue by lehrenberg** [htw-imi-info3/lab-06-railsapp-HTW#75]
![harry_potter_pumpkin](https://cloud.githubusercontent.com/assets/9266359/5922696/ff2b11f8-a64d-11e4-91cb-8e61fa32c6d8.jpg)

**Comment by jorin-vogel** [comment]
![bla](http://www.spritestitch.com/wp-content/uploads/2009/10/goombapumpkin.jpg)

**Comment by jorin-vogel** [comment]
![...](http://www.ryansgoblog.com/images/mario_pumpkin.jpg)

**Comment by lehrenberg** [comment]
![.....](http://fc01.deviantart.net/fs70/i/2012/300/2/2/harry_potter_hogwarts_crest_pumpkin_by_xrebel666x-d5j2pex.jpg)
